apiVersion: v1
kind: Service
metadata:
  name: {{ include "datatrip.fullname" . }}-backend
  labels:
    {{- include "datatrip.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: http
      name: http
      protocol: TCP
  selector:
    {{- include "datatrip.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend