apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datatrip.fullname" . }}-backend-secret
  labels:
    {{- include "datatrip.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.jwt.secret | quote }}
  {{- if and .Values.postgres.enabled (not .Values.postgres.host) .Values.postgres.internal.enabled }}
  postgres-password: {{ .Values.postgres.password | quote }}
  {{- end }}