apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datatrip.fullname" . }}-web
  labels:
    {{- include "datatrip.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.replicaCount.web }}
  selector:
    matchLabels:
      {{- include "datatrip.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "datatrip.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.web.repository }}:{{ .Values.image.web.tag }}"
          imagePullPolicy: {{ .Values.image.web.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.web.port }}
              name: http
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.web | nindent 12 }}